name: Sync Organization Repo to Personal Repo

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Organization Repo
        uses: actions/checkout@v3
        with:
          repository: Colauncha/Auctora-Frontend # Replace with your organization's repo
          ref: ${{ github.ref_name }}

      - name: Configure Git
        run: |
          git config --global user.email "colauncha@gmail.com"
          git config --global user.name "colauncha-dev"

      - name: Clone Personal Repo
        uses: actions/checkout@v3
        with:
          repository: colauncha-dev/auctora-frontend # Replace with your personal repo
          path: personal-repo
          token: ${{ secrets.OWNER }}

      - name: Verify Remote Origin
        run: |
          cd personal-repo
          git remote -v

      - name: Copy Files
        run: |
              mkdir -p temp_dir
              rsync -av --delete ./ temp_dir/
              rsync -av --delete temp_dir/ personal-repo/

      - name: Check Git Status
        run: |
          cd personal-repo
          git status

      - name: Commit and Push to Personal Repo
        run: |
              cd personal-repo
              git add .
              git commit -m "Sync from organization repo" || echo "No changes to commit"
              git push origin main --force
              cd ..
              rm -rf personal-repo
        env:
          PERSONAL_REPO_TOKEN: ${{ secrets.OWNER }}
